#!/usr/bin/env bash
# Installs Nginx with the following configurations:
#+    Listens on port 80.
#+    Returns a page content given
#+     at the root with a curl GET request.
#+    Configures /redirect_me as a "301 Moved Permanently".
#+    Includes a custom 404 page containing "Ceci n'est pas une page".
#+    Contains a custom HTTP header named X-Served-By.
#+    The value of the HTTP header is the hostname of the running server.

sudo apt-get -y update
sudo apt-get -y install nginx

echo "Hello World!" > /var/www/html/index.nginx-debian.html

echo "Ceci n'est pas une page" > /var/www/html/404.html

sudo sed -i "/server_name _;/a \
	\\\n\terror_page 404 /404.html; \
    \n\n\tadd_header X-Served-By $(hostname); \
	\n\n\tlocation /redirect_me { \
	\n\t\treturn 301 https://www.youtube.com/watch?v=QH2-TGUlwu4; \
	\n\t}" /etc/nginx/sites-available/default
service nginx restart

